Ndim_ := 4:
x1_ := eta:
x2_ := r:
x3_ := theta:
x4_ := phi:
sig_ := 2:
complex_ := {}:
g11_ := -(((1-q)*eta)^(q/(1-q)))^2:
g22_ := (((1-q)*eta)^(q/(1-q)))^2:
g33_ := (((1-q)*eta)^(q/(1-q)))^2*r^2:
g44_ := (((1-q)*eta)^(q/(1-q)))^2*r^4*sin(theta)^2:
Info_ := `Equation H.23, Carroll, Copyright GRTensor.org`:
