Ndim_ := 4:
x1_ := t:
x2_ := r:
x3_ := theta:
x4_ := phi:
sig_ := 2:
complex_ := {}:
g11_ := -1:
g22_ := (t^q)^2:
g33_ := (t^q)^2*r^2:
g44_ := (t^q)^2*sin(theta)^2*r^2:
Info_ := `Equation H.18, Carroll, Copyright GRTensor.org`:
