Ndim_ := 6:
x1_ := t:
x2_ := r:
x3_ := theta:
x4_ := phi:
x5_   := delta:
x6_   := epsilon:
sig_ := 4:
complex_ := {}:
g11_ := -F(r)^S:
g22_ := F(r)^(A-1):
g33_ := F(r)^A*r^2:
g44_ := F(r)^A*r^2*sin(theta)^2:
g55_ := F(r)^A*r^2*sin(theta)^2*sin(phi)^2:
g66_   :=F(r)^A*r^2*sin(theta)^2*sin(phi)^2*sin(delta)^2:
