Ndim_ :=    4   :
x1_   :=   r   :
x2_   :=   v   :
x3_   :=   theta   :
x4_   :=   phi   :
g12_   :=   c1(r)   :
g22_   :=   -c2(r)   :
g33_   :=   r^2   :
g44_   :=   r^2*sin(theta)^2   :
Info_ := `     Spherical Bondi metric in advanced coordinates (Proc. R. Soc. London A281,39)   `: 
constraint_:=[]:
