Ndim_ :=    4   :
x1_   :=   r   :
x2_   :=   v   :
x3_   :=   theta   :
x4_   :=   phi   :
g12_   :=   1   :
g22_   :=   -1+2*m/r   :
g33_   :=   r^2   :
g44_   :=   r^2*sin(theta)^2   :
Info_:= `The Schwarzschild metric in ingoing Eddington-Finkelstein coordinates (MTW Box 31.2)  `: 
