Ndim_ :=   4  :
x1_   :=   r  :
x2_   :=   theta   :
x3_   :=   phi   :
x4_   := delta:
complex_ := {}:
g11_   :=   1 :
g22_   :=   r^2   :
g33_   :=   r^2*sin(theta)^2   :
g44_   :=   r^2*sin(theta)^2*sin(phi)^2:
Info_:=`hypersph2 `:
