Ndim_ :=   4   :
x1_   :=   theta   :
x2_   :=   phi   :
x3_   := delta:
x4_   := epsilon:
complex_ := {}:
g11_   :=   r^2   :
g22_   :=   r^2*sin(theta)^2   :
g33_   :=   r^2*sin(theta)^2*sin(phi)^2:
g44_   :=   r^2*sin(theta)^2*sin(phi)^2*sin(delta)^2:
constraint_ :=   []   :
Info_:=`hyper`:
