Ndim_ :=   4   :
x1_   :=   u   :
x2_   :=   w   :
x3_   :=   theta   :
x4_   :=   phi   :
complex_ := {}:
sig_:=2:
g11_   :=   f(u,w) :
g12_   :=   h(u,w)   :
g33_   :=   r(u,w)^2   :
g44_   :=   r(u,w)^2*sin(theta)^2   :
Info_:=`Israel coordinates (Phys. Rev. 143,1016)`:
