Ndim_ :=    5   :
x1_    :=    r   :
x2_    :=    theta   :
x3_    :=    phi   :
x4_    :=    t   :
x5_    :=    x   :
sig_:=2:
g11_    :=    1/(1-2*m/r)   :
g22_    :=  1*r^2   :
g33_    :=    1*r^2*sin(theta)^2  :
g44_    :=    -(1-2*m/r)  :
g45_    :=    1:
Info_:=`The Schwarzschild metric in curvature coordinates`:
