Ndim_ :=    4   :
x1_    :=    r   :
x2_    :=    theta   :
x3_    :=    phi   :
x4_    :=    t   :
g11_    :=    a/(1-2*m/r)   :
g22_    :=    a*r^2   :
g33_    :=    a*r^2*sin(theta)^2   :
g44_    :=    a*(-1+2*m/r)   :
Info_:=`The Schwarzschild metric in curvature coordinates`:
