Ndim_ :=   6   :
x1_   :=   t   :
x2_   :=   r  :
x3_   :=   theta   :
x4_   :=   phi   :
x5_   := delta:
x6_   := epsilon:
complex_ := {}:
sig_:=4:
g11_   :=   -F(r) :
g22_   :=   1/ F(r) :
g33_   :=   r^2   :
g44_   :=   r^2*sin(theta)^2   :
g55_   :=   r^2*sin(theta)^2*sin(phi)^2:
g66_   :=   1:
Info_:=`Schwarzschild-Flat `:
