Ndim_ :=   5   :
x1_   :=   t   :
x2_   :=   r  :
x3_   :=   theta   :
x4_   :=   phi   :
x5_   := delta:
complex_ := {}:
sig_:=4:
g11_   :=   -(1-2*m/r) :
g22_   :=   1/ (1-2*m/r) :
g33_   :=   r^2   :
g44_   :=   r^2*sin(theta)^2   :
g55_   :=   1:
Info_:=`Schwarzschild-Flat `:
