Ndim_ :=   5   :
x1_   :=   t   :
x2_   :=   r  :
x3_   :=   theta   :
x4_   :=   phi   :
x5_   := delta:
complex_ := {}:
sig_:=4:
g11_   :=   -F(r) :
g22_   :=   1/ F(r) :
g33_   :=   r^2   :
g44_   :=   r^2*sin(theta)^2   :
g55_   :=   f(theta,phi):
Info_:=`Schwarzschild-Flat `:
