Ndim_ :=    5  :
x1_   :=   r   :
x2_   :=   theta   :
x3_   :=   phi   :
x4_   :=   t   :
x5_   :=x:
g11_   :=   1/g(r)  :
g22_   :=   r^2   :
g33_   :=   r^2*sin(theta)^2   :
g44_   :=   -f(r)   :
g55_   :=   -h(t)   :
